hash-format = "sha256"

[[files]]
file = "LICENSE"
hash = "d50991555d8829ebf8e18c833b7b91b4273d8790a55c6fe498b531be56be3e6a"

[[files]]
file = "mods/alexs-caves.pw.toml"
hash = "0cbc4b2c6b58b7a94f030ae84f18057e5dc78a17bad429f40b8884926a6ab233"
metafile = true

[[files]]
file = "mods/another-furniture.pw.toml"
hash = "90b4a61d7ee6099dc34cf85f099299293401b87fc8f3ca07ed59262c1c63c5a5"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "4e81241ba2da06f425efc5e09fb6b38470125c1581c39e1310c5843a0b96ec76"
metafile = true

[[files]]
file = "mods/automobility.pw.toml"
hash = "e0b0d4ffb66d813a4e6da0910d8e050bbfd8e16731dacb78fc5478029932c473"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "fec49033058ced91f7668d4e305e599f5527501ef37c1f30f96d8927d6202d32"
metafile = true

[[files]]
file = "mods/building-wands.pw.toml"
hash = "e5ebcdd6314ddad2309c7db52a0b70f4472bf8b118c2cefe64f64193ef57af83"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "c45dce6b9e52796c0606ff222efa5833fd1d420fa67e7a8f26852196b80f6fa5"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "b0732421ae2999d558a7b70a11fa86a93738ca33f6f3ec343017796df9c47d9c"
metafile = true

[[files]]
file = "mods/citadel.pw.toml"
hash = "c7ac7f84731a0ca1fefb3491c3f65c2767afd4be207e094fcb65c4cea99c9549"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "e3dd03e7fec88831974857e2cdded54dd5c5bdcaa3f6d6248c2800e82db4dd41"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "853df4ab2418f347cbb1e3b4ca6c82b2a517a8e4e8ccabcd42c27e3496707a32"
metafile = true

[[files]]
file = "mods/create-cardboarded-conveynience.pw.toml"
hash = "6d3f54b36d50a927f353b8a182f656e549b3cd4fce38774ba79df4d1cafe47cd"
metafile = true

[[files]]
file = "mods/create-clockwork.pw.toml"
hash = "5021b4a0f5474201447787ebe98a5d6cf3d18b10e06fe64f726608e4739e8a9f"
metafile = true

[[files]]
file = "mods/create-connected.pw.toml"
hash = "aa8711ff3f1d590b8c3e4e092927e5a697d585e21c52107ddc559c93ffebdaed"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
hash = "c670ae9055f10dafb61fe340583c361f4c41ed45671c9440bae1f0696b47252a"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "fb5c251cf4997fa65ca043bab7c9ecbd02e108031584a3e26276b77d212de23c"
metafile = true

[[files]]
file = "mods/create_factory_logistics.pw.toml"
hash = "0b84aa4d342abf1b0a1afbab8b4fb8d21e095eece08b949f13e40bb6f100e031"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "e6d1f36e9e0193fe410d136e0cda8a7f6dbbc809c0644f06a601bddf5b38a395"
metafile = true

[[files]]
file = "mods/critters-and-companions.pw.toml"
hash = "6292625ed60e17068f3e7927d26c75053b64269c922f10b1c87ceea51ccb194e"
metafile = true

[[files]]
file = "mods/diagonal-fences.pw.toml"
hash = "31bec9d75cc9e7e00e3b564c7ad5ff161840a7f5d2a6e39e6ba4672b15ed2040"
metafile = true

[[files]]
file = "mods/diagonal-walls.pw.toml"
hash = "8a0376d17bc64c6fc4d3097b20daf4c5da22735fafb4d5b2dc90a074694ffae1"
metafile = true

[[files]]
file = "mods/diagonal-windows.pw.toml"
hash = "d83cb449f28672c09c80987e2321bfa13aa6127a814ef6007185575ba0173e0a"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "47fd33da68d0b13cdffd4124f5bc9cff64caa2878ce7e979ba8092400c2ae1eb"
metafile = true

[[files]]
file = "mods/do-api.pw.toml"
hash = "35e3ed00b7e0b2a3082ed35c677589ca762cd73e18858ad6ba7a4b6f7cdef441"
metafile = true

[[files]]
file = "mods/elysium-api.pw.toml"
hash = "4e77452de64a8038260a173a36702830e264bf23b47bc12f33ebbcdc52e8d519"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "9f2ffb0d4c65fcb2a96878287a7119459b9d0637c395e5097d691416690d6563"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "1030e18f2e875dfdf39de82b823e1dfe6009f21f1aaad338137d3a90504e2f7e"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "71f185e62d546881244d4b5a213ebc3d2d6df14b0218c0e5dd6426fcb22cb55f"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "db495b3ac268709a2ba673bfe220b10257fb7dae549f94bfbd539617d571f131"
metafile = true

[[files]]
file = "mods/immersive-aircraft.pw.toml"
hash = "d150fa1845c5cd2b017c202e1792a6fe5c5155c34ceb710213370d8d83819924"
metafile = true

[[files]]
file = "mods/immersive-paintings.pw.toml"
hash = "3aa4d2e503b7a4544868954aa8175335ee34714a8b44cc2a41cdbb833e271c31"
metafile = true

[[files]]
file = "mods/interactive.pw.toml"
hash = "7442eedee93f3797e9bedce849d5a41bdb4b8a26255ee47090caaaee961887f1"
metafile = true

[[files]]
file = "mods/jadens-nether-expansion.pw.toml"
hash = "18fdaa8b6729867b1862ea80eba84effc90f63b8d230eb529c5a949b30ae2695"
metafile = true

[[files]]
file = "mods/joy-of-painting.pw.toml"
hash = "dca44614a72da5f7d2d57823cc54aaf3335d652c1a447a6e5df2e60365a6ea95"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "70a4ecd9d0c04ad20aeb976c1ee28933ce48a0a1f43df42deafaeb2ad7235297"
metafile = true

[[files]]
file = "mods/leaves-be-gone.pw.toml"
hash = "9a5e498a9c596fb0bfbab74173aa854257466e8c538d15c1966ce268b3267575"
metafile = true

[[files]]
file = "mods/lets-do-bakery.pw.toml"
hash = "f3a7eccc267e6dcb2fc6b7abf6ebdab54c0f45da768c169e967c4db7529dfa81"
metafile = true

[[files]]
file = "mods/lets-do-brewery.pw.toml"
hash = "16bd1aacc8879f8b4bfb9c973f758af6af37e3fc91c45f740f39e01b0dd4ad4d"
metafile = true

[[files]]
file = "mods/lets-do-candlelight.pw.toml"
hash = "a7172dfca9838e101e0b6f7db545a04f82734847b394f54e14a8450f97781a0c"
metafile = true

[[files]]
file = "mods/music-maker-mod.pw.toml"
hash = "89c6efe2b6bd0fdd7d47f8a9611fced3a4f21046c5d4a45538e14b5acfd25106"
metafile = true

[[files]]
file = "mods/nightlights.pw.toml"
hash = "b8cb0e090011a9d2ed6fcf7007d19efc67b8d911300531054b46d1f41d54dd9e"
metafile = true

[[files]]
file = "mods/petrolpark.pw.toml"
hash = "20b656798b6afb8ed1133cc7cd7ac5c61a8f73e49f321544e4ac554620167fb1"
metafile = true

[[files]]
file = "mods/petrols-parts.pw.toml"
hash = "7165e1854d27fbe4448eaee9c797d40a5039548f6b127c79558e8da8c47592e6"
metafile = true

[[files]]
file = "mods/plushie.pw.toml"
hash = "99b0c10c575e0dde89e6c856fc4576a3e68e998861f1be53ff462e3b79b22203"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "4dd7038889da90e145f9d074bec64a61aaae12dc57c875aa7ad99b8b2e07979b"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "5c07edd0c8fe82e85efd6c027476ba54cf98291526803b74614c3436292e4ab6"
metafile = true

[[files]]
file = "mods/ribbits.pw.toml"
hash = "ca5d254eded2a38a5db675f464d2fe355c633a2f774b9d4e2937163639a8b98e"
metafile = true

[[files]]
file = "mods/serene-seasons.pw.toml"
hash = "7f38bb5c863c04b013a2c6ed75d799525ba3cc5a548279adde6e9329ff308dd4"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
hash = "f49c7302f7a044aae67740fac3a7558ca2f26b3a89a69a3940d516a40e3b75b7"
metafile = true

[[files]]
file = "mods/species.pw.toml"
hash = "50d0cb105f5db0a982d9c00f5ea6aee826866576b796526686ab0877c912e968"
metafile = true

[[files]]
file = "mods/stitch.pw.toml"
hash = "58621f030d6291279635fcaf62bffdea007077aaf98513057a59fe97d0ddce6d"
metafile = true

[[files]]
file = "mods/straw-statues.pw.toml"
hash = "791be45440111d5edac5246dc8db707e25f5534783212ebe3909ad40b7230a4b"
metafile = true

[[files]]
file = "mods/valkyrien-skies.pw.toml"
hash = "24332be98ab9c9250af31714c85785b6790bddc2def491e1ba6d249defa714ae"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "50dfd8547f93d1bc8f31e1740f94e24aadf661cb2948587ac16a41404b10effd"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "152c6732da180e958fb29f492bae2e468d4dfd423ce4d3d0d31ef31c2eec6c61"
metafile = true
